##########################
# COMMENTS
##########################

seed_comments = ["Looks so big ❤️",
"Precious!!",
"Very sweet!",
"LOVE!!",
"laila is too cute",
"Looks adorable!",
"So cute.",
"So crazy and funny, Shana!:)",
"Great picture!",
"Very neat capture here",
"Nice!",
"beautiful capture!",
"Great shot!!",
"How cool!",
"Love this..so simple and perfect",
"what a great trip, are you there right now?",
"Great image !",
"USA is an amazing nation ❤️",
"Wow!  I really like this pic for a poster.",
"Great photo! Love all the different directions...so many choices!!",
"Great picture!",
"Beautiful scene",
"excellent!!",
"Not under the rain, but sure",
"🎼Love is in the rain, everywhere I look around🎼",
"I wonder what side is this, US or Canadian side?",
"Difficult to find a good picture of this place, you nailed it !",
"Excellent shot!",
"Awesome",
"This picture is awesome.",
"Seriously! And great great work!!",
"Yeah, funny how things work....anyone who meets Chana is stuck with us FOREVER.",
"awesome picture! :)",
"Love the colors!",
"Great photo! Love the expression!",
"Beautiful tones!",
"Love this photo! Well done!",
"❤️ ❤️",
"Very Nice!!",
"I love that you can tell how big his smile is even though he is looking down!",
"Love this!!",
"Great image!",
"its not age that gives inspiration, it\'s spirit!",
"Amazing.",
"Love this! ❤",
"great shot!! :)",
"\"Hold my whine I will show you how this is done\"",
"Oh my gosh! How fun!",
"Great job boys.",
"Love the depth of field and the peak of the kid in the background smiling! Great shot!",
"There so cute!",
"This is such a great photo in so many ways!",
"Beautiful picture",
"Teamwork!",
"Love it!",
"How sweet! Love this ❤",
"Such a great opportunity to bond!",
"I love this candid, it is so sweet.",
"Team work is great",
"great photo ...almost commercial",
"Great moment! So sweet!",
"very cute.",
"This is so cute!!",
"That\'s adorable <3",
"Great idea",
"Did you make that!? Oh awesome",
"How cute!",
"Fun!",
"Oh how cute!!",
"So cute!!",
"So creative!",
"Yum! What a fun photo!",
"Those are cool!",
"awesome!!",
"Great idea! How creative!",
"this is really pretty!!!",
"so much fun!",
"So fun and pretty!",
"Yummy! And cute!",
"Yum!",
"Aww how adorable! Looks delicious <3",
"Very cute",
"Lovely! ❤",
"Gorgeous!",
"This is so pretty!",
"So pretty!",
"Blessings on the new year!",
"I wish I was there!",
"This is just lovely",
"Beautiful",
"Beautiful 😍😍😍",
"Love the reflection",
"so gorgeous!",
"Gorgeous photo! ❤",
"breathtaking",
"Gorgeous!",
"Love the reflection!",
"Love this!!!",
"If only I saw this every day...",
"pretty",
"Gorgeous sunset!",
"I miss sand and palm trees!!",
"this is beautiful!",
"Gorgeous",
"😍 Wow! 😍",
"This is gorgeous!!",
"Love this",
"Great photo! ❤",
"Wow! Love this!",
"Oh, I miss the sea!",
"love your composition.",
"Beautiful",
"Stunning",
"This is stunning <3",
"Absolutely gorgeous!",
"Wow.",
"Love the atmosphere in this photo!",
"Wonderful",
"Sure is a cutie! Happy Chanukah!",
"Such a fun moment to preserve!",
"Aww! This is perfect moment!",
"Such a great photo!",
"This is cute",
"Adorable!",
"Aw <3",
"So sweet",
"This makes me so happy! <3",
"Amazing shot!",
"Perfect moment!",
"Love this! ❤",
"Great moment!",
"timeless moment. I love this one too !",
"❤",
"❄❄❄😍",
"Love these colors!",
"Gorgeous portrait!",
"Love the colorful background",
"I love how beautiful she is, and that wall color completes the picture perfectly.",
"gorgeous!",
"Amazing shot!",
"beautiful!",
"The colored background just makes her pop. Beautiful!",
"Great job!  The colors are stunning and so is your model!",
"Love!",
"She is beautiful!",
"Gorgeous shot! I love that wall!",
"Love this",
"Great photo! ❤",
"Beautiful image!!",
"We need to bring fall leaves here again 😉",
"Me!!!!!",
"I will try my best!",
"Woot woot... Nice",
"Love her smile!",
"Love ❤",
"bella..",
"I wish to meet you someday Ms. Lara Jade",
"Beautiful inspiration",
"OMG😍",
"This is a nice photo. With plenty of interpretation. Really like this one.  Thanks for sharing.",
"Hi, I am looking for a continuous light and large octogonal softbox like yours! So difficult to find in France. Could you please tell the brand of the light and softbox? It would be so kind of you! Have  a nice day, regards",
"LOVE THIS!!! LOOKS AMAZING!",
"Spectacular image.  I bow to genius.",
"Love the color....",
"Beautiful, I just took some new ones myself but the model wasn\'t exactly graceful in the water and the photos show.",
"Beautiful color ☺",
"Candice.   Engelmeyer.   Beautiful",
"That\'s amazing",
"Beautiful!!",
"Great click",
"Sooo Beautiful!",
"Helene Quaxo Quin",
"En el mar pega Claudia Ibañez Tufiño",
"Nice one",
"Beautiful‼︎",
"Jyong Han Chen",
"🙌",
"Oosman Sadiq",
"😍 Ben Dennis",
"Candice.  Engelmeyer.   Beautiful",
"I love how you view the world 💦💙💦",
"WOW!!!",
"Very nice👏👏👏",
"So perfect and amazing.",
"impressive",
"Irish dapat mala ganitong shot gawin natin lol",
"wow!",
"Julie Nguyen",
"super..",
"Rhita",
"Awesome !",
"Just breathtaking !",
"Beautiful",
"Awesome",
"Aiya lets achieve this kind of you know",
"An amazing shot from both sides of the camera! Can\'t imagine all the other you had to go through choose the best one...It\'s the toughest part about editing!",
"Sideral dance",
"Beautiful",
"💞",
"Any Twitter or IG pages???",
"Amazing. (-:",
"Amazing!",
"Wow",
"Cynthia Terminel",
"Lov this",
"So lovely.",
"Perfection.....",
"Amazing shot 💞💞💞💞",
"Kieran Denning everything you want in a women 😍😍😉",
"Just amazing and beautiful",
"Awesome!!",
"How good would it be to do this for our 50th Leicha !! Absolutely love this photographers work! 💙",
"Hermoso <3",
"Emma Pardon M!!!! U need to do this 😊",
"Luvvvv",
"Salutación al sol aguamarina.",
"Millie Russell",
"Wonderful",
"Pure magic! Thanks for sharing 💫 💕 💞",
":-).",
"Wow awesome picture 👍",
"AWWWWWSSSSSSSSSOMEEEEE",
"Beautiful graphics",
"Corinne how we think we look in the go pro pictures 😂😂😂",
"Cudne",
"Perfect photography..good choice.. Perfect light.. Im impressed by your vision..",
"Awesome shot!",
"Sunshine raggea",
"Stunning 💜💜💜💜",
"Definitely have to slide your feet along the sand there due to the rays",
"Bellissima!",
"I love your photo so much !!",
"Zo S Sol Lovely shot!",
"Sublime !",
"Beautiful pictures with beautiful women!",
"beautiful",
"Brilliant photo.",
"👌😀",
"I want to model for youuuu 😭",
"How much would a picture like this cost if I wanted to buy",
"Wow , awesome.",
"Wonderful, lucky I stumbled   upon this photo effects  place :)",
"Wonderful",
"nice",
"Beautiful",
"Great picture!",
"wow! Beautiful!!",
"Dope!",
"😮😍❤️",
"Mika Mely",
"This photo is so cool! I used to snorkel, parasail, and do anything water related because it\'s so beautiful under the surface of the water. Once you get your gear on and look below the surface of any ocean, it\'s colors and beauty are incredible, especially the Carribean. I have been to several Carribbean locations but the Bahamas, although not very pleasant on the island itself, has the most beautiful waters I have ever seen.",
"Awesome! <3",
"your work is breathtaking..... so original and so very beautiful",
"Candice.  Engelmeyer.  Beautiful",
"Can you buy it the picture",
"bliss",
"Crazy good! How do you get the images so sharp? Are you hand holding or have you weighted down your tripod?",
"Great thanks a lot  love lighting",
"Israel, booooora cabeca!",
"💙",
"nice beautiful",
"Wonderful 👍🙆",
"Beautiful !",
"Awesome",
"Beautiful",
"Very spacticular",
"Oh my goodness. <3",
"Your works are authentic no doubt on that, But I always been wondered how long you keep your breathe tight  :D Hatsoff lady♥",
"Really awesome!",
"This is truly amazing and beautiful <3",
"Really amazing",
"Superb.",
"mesmerizing. wow.",
"<3",
"Ang ganda nmn!",
"Beautiful, beautiful world  <3",
"One of my fav :3",
"Eso es  un hermoso sueño, en belleza natural. Sorprendente..!",
"Yeah he is a hero for many",
"unreal beautiful  ....",
"That\'s cool 😊",
"very nice Elena!!",
"So beautiful <3",
"So soothing under the sea",
"increíble",
"What equipment do you use to take shots like this! Xxx",
"That hands down beats the bottom of my pool. :)",
"Do you sell the pictures",
"Your shots always make me lose my breath for a few seconds. Consistently spellbinding.",
"who else digs photography",
"Really wonderful  !!!!",
"Stuff  like this is why  everyone loves Instants",
"<3",
"Is there no end to your imagination?",
"Fabulous photograph !",
"AMAZING  KIND OF PHOTOGRAPHY",
"💙💙💙💙💙",
"Looks like a 3D painting.",
"stunning.",
"~Beautiful! 💙~",
"Magnifique",
"Magnifii",
"Wow, beautiful!",
"Beautiful 😊",
"A few drops?",
"Mohamed Hamdi.  Great words",
"superbe ;)",
"Wonderful!",
"Claire Cowan so pretty",
"💜",
"Sinem Cetinkaya",
"Super",
"Brooke Reeves",
"You are something the whole universe is doing, in the same way the wave is something the whole ocean is doing.",
"It\'s no longer a few drops though is it....sad to say but it\'s gigantic corporations who put profit before health all for short term gain.....is that Japanese reactor still spewing radioactive into the sea....over 12 months now and they don\'t know how to stop it....it\'s not magically cured itself!",
"Beautiful 😍",
"Love the picture and the quote.",
"luv this <3",
"thank you beautiful picture!!!",
"Wooooooooooow",
"But drops of water do makes an ocean!",
"You are professional photographer Elena, amazing photo & inspiring qoute..... :)",
"👍",
"!!!!!!!!",
"stunning beautiful",
"Glorious! Both sentiment and photo!",
"Beautiful",
"Pamee M Bermudez",
"Rochelle this is the photographer I was telling you about. How awesome would this be for a 50th shoot!! 💙💙",
"Stunningly beautiful!",
"beautiful <3",
"Loooove the tones.",
"Parabens",
"Gina",
"I want to do a shoot like this so badly. Beautiful",
"Absolutely beautiful!",
"Oh wow, I love this colors!",
"very nice photo",
"Stunning!",
"😮 love it ❤️🙏",
"Nice :)",
"Amazing",
"wow! beautiful <3",
"Ethereal!!",
"Love!!! 😍",
"Laura Barrett-Elfering⚡️",
"Beautiful! 😻",
"Prachtig",
"Would you alĺow me to make a painting based on your photo? Magnificent",
"I <3 your photos, thanks for this beauty.",
"~",
"incredible shoot... beautiful !!! Well done!!",
"Celeste mi tía jaja",
"Beautiful",
"Dee Anne Enriquez!!!!",
"Chrissi Desconocida wir müssen auf die Bahamas und das Foto wiederholen :D",
"Beautifil",
"Mariana Rivas",
"Mimi just like your dreamy shoot!",
"Manuel Rauchberger solche Fotos",
"Awesome!",
"Wow 😱😄",
"Thiago Caetano olha!",
"Beautiful...!",
"Laura :\'(",
"Just beautiful!",
"Vanessa Teklenburg",
"Welcome back!",
"Magnifique!",
"Fantasy meets inexplicable beauty",
"beautaiful!!!!",
"Alexandra <3 Let\'s travel somewhere and do this plz",
"Your model is amazing! The photo turned out fantastic.",
"Millie Harvey",
"Brenda, makes me think of you!",
"Perfect!!!!!  ♡",
"beautiful",
"מדהימה כתמיד",
"Superb😍",
"J played music on these photos on YOU TUBE!",
"BETWEEN BLUE AND WHITE",
"Tangled in fishing gear?",
"Superb !!!!!",
"Beautiful....",
"Tracy Olive",
"So beautiful",
"Beautifuuuul! 💖",
"I would like to be in your pictures under water that would be amazing!",
"so Beautiful!!",
"Wow !",
"Im ready when you are Hillary Head",
"Your work blows my mind!! Absolutely breath taking!!",
"Splendid!!!",
"Beautiful!",
"Wow. Looks like a jellyfish floating",
"Lukas lets do it :)",
"Glad to hear from you since the hurricane. Everything okay?",
"Beautiful",
"lovley",
"I wish I could too!",
"Que hermosa",
"Azar Hassan",
"Waw!",
"Amazing would even look just as amazing upside down",
"GRACIAS,ELENA.",
"COOL!",
"We could be doing this! Raphael",
"So so beautiful and cool and quiet, just listen your heart...",
"amazing!!!",
"Hi, where can I purchase a print of your work?",
"congratulations you are one of top 10 best photographers in the world. You rate num. 2.............",
"So beautiful",
"amazing! <3",
"yes beautiful<3",
"<3",
"Abhimanyu Drall Life Goals.",
"amazing",
"Great capture!",
"Leah Savarie",
"Fentastic",
"Raynier Villalobos",
"wonderful!!!",
"takes me to a world that is my true soul",
"Super beautiful! Love it!",
"ABSOLUTELY GORGEOUS!",
"Angy Ermus",
"Wow. I can\'t wait to shoot in clear water beaches one day. Checkout my stuff!",
"GOAL",
"Where\'s the shoot location!?",
"Samir Lovejoy mad doh?",
"Wow!!!",
"Damn you\'re good :-) Great shot.",
"Nice pic!!!😍",
"Santos, are the waters of Bermuda this lovely too ?",
"Awesome",
"Beautiful !",
"Sharks !!!!",
"Awesome",
"Simply amazing, what a shot!",
"amazing shot 👌 love it !",
"Beautiful!",
"Love the pic",
"Sexy as hell",
"Awesome",
"Nsss",
"Stunning",
"I want to model something like this so bad",
"beautiful",
"Amazing! Bella foto",
"Wow !",
"It\'s just awesome !!!",
"Winny Lay",
"Amazing!! <3",
"Beautiful 😍",
"Caroline Elizabeth Jarvis",
"You look like a beautiful mermaid!!!",
"Love this shot",
"stunning..<3",
"Madi let\'s take water pics",
"Sublime",
"Fabulous",
"Gorgeous   ,!!",
"Wow",
"this is absolutely amazing!",
"!!!!!!!!!!!!....",
"Woah!!! Love this!!",
"When do we go Stefanie",
"Bella imagen!!!",
"Awesome☺︎",
"I LOVE THIS",
"beauty world‼️",
"Wow!!!",
"So beautiful.",
"Wow  fasination",
"I guess  shoot location  is  bahama sea",
"Amazing",
"J\'adore",
"Beautiful",
"Nice",
"Maximilian Stinson",
"The Bahamas are super shallow in some places...",
"<3",
"<3",
"Love your photos !! Absolutly awesome !! 🌊🌊🌊",
"Beautiful",
"Dulce Ruiz our next level underwater shoot :D",
"Nice pic 😉",
"That water...",
"I have that saying on a wall hanging.",
"Very nice !!",
"Amazing!",
"Wonderful, as always",
"Love it",
"I\'d love to do a shoot like this. Amazing",
"This is neat. I love cool underwater shots! :D",
"This picture is amazing beyond words😊❤️👌",
"Beautiful",
"Amazing photo!!!!   <3",
"Stunning pic Elena and Sacha!",
"Lorna Marie Ryan reminds me of a pic you took under water!",
"So pure words and lovely pic",
"Incredible <3",
"Lapodoré",
"Absolutely Beautiful!!! I miss seeing you! I hope all is wonderful!",
"Brenda Czermak",
"You are the best. Rabin is the greatest .",
"massive",
"breath taking",
"I like this photo !!!",
"Rachel Hughes",
"Magnificent!! Hauntingly magical....",
"Ana 😔😭😭❤️",
"Incredible shot!😊",
"My favorite love poem of ALL TIME❤️",
"Nice",
"gorgeous..shared with luv <3 TY",
"This is amazing! I would love to work with you!",
"Woaaaawww",
"Barbie",
"We are makeing gliding under water  on fast way ....we know how to move up &down always under water .....",
"Tim Braitling",
"I love your work so much. :)",
"I like this photography and also like the poetry .",
"Lisa Burgoyne Blanzy.. This is so cool...",
"like a mermaid",
"Cette photo est sublime",
"Marty this is my dream photoshoot!! 😍😍",
"Sharni haha I thought u were talkin bout the caption tbh 😞",
"Ur works are awesome",
"ღ•°*”˜ღ•°*”˜ ·٠•●*♫•* ♫♪",
"Erik possible model for you?",
"Love love love it",
"Lovely!",
"BEAUTIFUL AS MUCH AS UTMOST HEIGHTS OF BEAUTY COULD BE!!!",
"bellooooo",
"I\'m in love with your photos 💙",
"I wisch.... I was there ...in water....💜💜",
"Kristi 😍😍 I soo need that underwater housing!",
"Nice work",
"Bahamas is just beautiful",
"This is outstanding shot.",
"wow",
"These pics are so perfect.",
"que linda",
"So otherworldly...",
"Summer Rad this chicks photography skills",
"Beauty",
"great work !!!!",
"Brilliant !",
"Amazing!",
"Super",
"Wauw nice :)",
"I love Bahamas Girl!",
"Great capture.  I would love to have you and your models in front of my lens.",
"Beautiful!!!",
"i adore you work so much....thank you for posting",
"She is really beautiful and graceful underwater.",
"is it hard to find models? and do you photoshop out bubbles? ? ?",
"super..",
"Beatiful model greatly photographed !",
"WOW.........",
"NiKi :D",
"beautiful pic nice",
"swim lady swim",
"hermooooosa",
"What camera do you use?",
":)",
"so much awesomeness",
"Woanderful,is good pic",
"Fantastic image",
"Wow! <3",
"Superbe",
"perfect !!",
"perfect so perfect",
"Awesome!*-*",
"beautiful",
"Awesome bro...",
"Amazing! <3",
"No word!",
"Wonderful picture!",
"😍😍😍",
"Boldly go where no Girl has gone before 😜",
"👍 super",
"Wow! Superb!!!",
"Fantastica ",
"Yumiko",
"This is so gorgeous.",
"This is gorgeous (Y)",
"AMAZING!!!1",
"Stunning!!",
"So mysticaly enchanting Ariel has nothing on you",
"That\'s why I dig fungus and bacteria.",
"Beautiful! Very nice piece!",
"So beautiful!",
"Good Morning Like this Pic Nice",
"Superbe.",
"Great piece of work! :) I adore your photos.",
"very nice",
"amazing!! mind blowin. I would love to click the above!!",
"wow great pic cant say in words",
"Yo quiero una",
"Amazing Photography !",
"amazing <3",
"nice",
"So beautiful!  Are your prints available for purchase?",
"Wow",
"Awesome!!!!!!!",
"Sajjad Saadat",
"Beautiful.",
"Raachel mira, hacemos unas? :)",
"wooow! <3",
"woooow",
"black white with little blue saphire",
"<3",
"Wow!",
"Nice pic",
"This is honestly just beautiful",
"Absolutely love it,  so angelic",
"I love it.",
"Gorgeous!",
"oooooohhhh que beeello",
"Loks",
"thanks",
"Amaazing",
"Perfection! :O",
"Seeing this it feels quite boring here in my forest. Even with the cat.",
"just love it",
"This is more entertaining than football.",
"nice pic",
"I like this amazing picture!",
"ya abal fazl.",
"I love your work, the pictures are always awesome dude! :D",
"Wow great shot!!",
"I really love your work Elena!",
"Wonderful",
"Fytrou Tania",
"Love it!!!!! we had such a wonderful time with you two <3",
"Perffffffection👈",
"Nice job!",
"<3 <3",
"love sea <3",
"truly amazing",
"wao",
"Those look like very big fish... Big Fish.. I should watch that movie.",
"Beautiful!!!",
"❤❤❤❤❤❤❤❤❤",
"Love your Art >)",
"I love morning traffic like this...,",
"The second one looks like my uncle Philip! 🐟",
"do u use any lighting..or natural light only",
"Amazing",
"pokonamah gelo pisan",
"Marvelous!",
"very nice",
"absolutely love it!",
"Wow",
"Cool pic. love the nurse Sharks.",
"Wow beautiful",
"OMG EPIC",
"Just wonderful!!",
"wow",
"nice feeling of togetherness"]

print "☠️  Destroying comments... "
Comment.destroy_all
puts "✅"
print "🗣 Seeding comments... "

seed_comments.each do |comment|
  comment_options = {
    post_id: SEED_POST_IDS.sample,
    body: comment,
    author_id: SEED_USERS.sample.id
  }
  Comment.create!(comment_options)
end

puts "✅"
