##########################
# POSTS
##########################

print "☠️  Destroying posts... "
Post.destroy_all
puts "✅"
print "📨 Seeding posts... "

seed_post_captions = ["Friday, my second favorite F word",
"Life isn’t perfect..But my Hair is! #selfieaddict",
"I didn’t choose the thug life, the thug life chose me.",
"When i was Rome.. I did what the Romans did.",
"With You, I forget all my problems. With You, Time Stands Still.",
"We come to love by not finding the perfect person but by learning to see imperfect person perfectly.",
"When I fell for you, I fell Hard",
"If I ever write story about my life, don’t be surprised if your name appears billion time.",
"I want you to be happy, but I want you to be happy with Me.",
"It will be Always YOU.",
"If you are Mine, You are Mine. I don’t like Sharing.",
"Nothing Can replace you!",
"I love you. That’s all I know.",
"I’m not perfect but I am Loyal.",
"Hey, I just met you, this is crazy",
"Stop looking for happiness in the same place you just lost it.",
"I woke up like this",
"If we could only turn back time…",
"Keep smiling because life is a beautiful thing and there’s so much to smile about.",
"Beauty is power; a smile is it’s sword",
"My autobiography is this",
"Proof that I can do selfies better than you",
"A friend will always make you Smile, specially when you don’t want to…",
"Life is like a balloon..If you never let go, you will not know how high can you rise.",
"Sometimes life can surprise you with a happy coincidence.",
"This is to the Echos of our laughter. The looks That we Share. The never ending gossips. and the Sudden amazing get aways. This is to our Past And This is to Our Future. This is to our Friendship that will Never Fade.",
"Life isn’t perfect..But my Hair is! #selfieaddict",
"Always classy, never trashy, and a little bit sassy.",
"It is not how much we have, but how much we enjoy, that makes happiness.",
"The most important thing is to enjoy your life – to be happy – it’s all that matters.",
"Life is not a problem to be solved, but a reality to be experienced.",
"I love those who can smile in trouble, who can gather strength from distress, and grow brave by reflection. ‘Tis the business of little minds to shrink, but they whose heart is firm, and whose conscience approves their conduct, will pursue their principles unto death.",
"It had long since come to my attention that people of accomplishment rarely sat back and let things happen to them. They went out and happened to things.",
"Love can be unselfish, in the sense of being benevolent and generous, without being selfless.",
"When I feel a little down, I put on my favorite high heels and dance",
"Life goes on, with or without you.",
"If you’re honestly happy, who cares what people think?",
"Own what’s yours, or else others will try to.",
"Life goes on, with or without you.",
"Don’t mistake my kindness for weakness.",
"You couldn’t handle me even if I came with instructions.",
"Forgive, yes. Forget, never.",
"There’s a hole in my heart where you use to be.",
"I don’t need any part-time people in my life.",
"“I would rather walk with a friend in the dark, than alone in the light.” —Helen Keller",
"Best Friends make good times better and hard times easier!",
"I don’t know what I did to have a best friend like you.",
"Life was meant for Best Friends and Good Adventures!",
"She is my Best Friend. You break her heart, I will break your face.",
"Good Times + Crazy Friends = Great Memories!",
"I don’t need your approval to be me.",
"I am who I am, I am what I am, I do what I do and I ain’t never gonna do it any different. I don’t care who likes it and who don’t.",
"Take me as I am, or watch me as I go.",
"If I were you, I would adore me.",
"Me? Weird? Please! I am Limited Edition.",
"I am not perfect. I make mistakes. But when I say Sorry… I mean it!",
"I am not trying to give an image of a fairy-tale, perfect, everything else, I am just being myself.",
"I was both loved and hated for being upfront. But I was just being myself.",
"I like being myself. Maybe just slimmer, with a few less wrinkles.",
"I take a lot of pride in being myself. I’m comfortable with who I am.",
"Don’t talk, just act. Don’t say, just show. Don’t promise, just prove.",
"Never stop doing great just because someone doesn’t give you credit.",
"It always seems impossible until it’s done.",
"Be honest.",
"Good things come to those who hustle.",
"If you want to succeed, you have to let failure be your best-friend!",
"You can’t do epic with basic people!",
"There is only one person in this world who I am in competition with—myself",
"Confidence level: Selfie with no filter.",
"Stay up off my Instants, pure temptation",
"Good times and tan lines",
"The most alluring thing a person can have is confidence",
"You don't worry about fitting in when you're custom made",
"First God created man, then he had a better idea",
"I liked memes before they were on Instants",
"At dawn, we ride",
"I wasn’t lucky, I deserved it",
"Oh, hi there!",
"Smile :)",
"We all start as strangers",
"Weekend, please don’t leave me.",
"Life is not measured by the number of breaths you take, but the moments that take your breath away",
"Guess what I just did",
"On my way to school :)",
"If I was funny, I would have a good Instants caption",
"Some days start better than others",
"Live the live you want to, not the one you’re supposed to",
"Trying to forget it but the memories are too strong",
"A clever person solves a problem. A wise person avoids it. A dumb person creates it.",
"That moment when you realize your childhood is over",
"I have made a huge mistake",
"Being famous on Instants is like being rich on Monopoly.",
"Stay strong, the weekend is coming",
"Instants is down, just describe your lunch to me",
"I’ll never try to fit in. I was born to STAND OUT.",
"I don’t always make sense, but when I do, I don’t",
"When Instants was down, I ran around town shouting “like” at flowers, dogs, and expensive brunches.",
"So, you’re on Instants? You must be an amazing photographer",
"Lives change like the weather. I hope you remember today is never too late to be brand new.",
"I don’t always study, but when I do, I don’t",
"I just got 30 likes, #selfiepro",
"The sun will shine someday",
"What do you think of the view?",
"I’ll do me",
"Life is better when you’re laughing",
"Some things are better in dreams",
"Sunday fun day",
"So jealous",
"Wish you were here",
"Getting my pose on",
"This could be the beginning",
"Smile, life is beautiful",
"Sandals and sunshine",
"My time is now",
"Just hanging with my friends",
"Never love anyone who treats you like you’re ordinary"]

SEED_POST_IDS = []

242.times do |n|
  post_options = {
    author_id: SEED_USERS.sample.id,
    caption: seed_post_captions.sample,
    created_at: Faker::Time.backward(365, :all),
    image: File.open("app/assets/images/instant-#{n+1}.jpg")
  }
  p = Post.create!(post_options)
  SEED_POST_IDS << p.id

end

puts "✅"
